# Generated by Django 5.0.4 on 2024-07-11 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gasoline', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surtidor',
            name='saldo_diesel',
        ),
        migrations.RemoveField(
            model_name='surtidor',
            name='saldo_gasolina',
        ),
        migrations.RemoveField(
            model_name='surtidor',
            name='saldo_gasolinapremium',
        ),
    ]
